echo Making dir for originals...
mkdir full_size
echo Moving originals to safe directory...
mv *.jpg *.JPG full_size/
echo Building thumb nails...
bash ../../thumb.sh
echo Building preview size...
bash ../../preview.sh
echo Building HTML indexes...
python ../../build.index.html.py
echo Done.
cd ..

